name = "Server Thingy"
author = "pixl_xip"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c84ee88c7bb44fa935808bd6c1918d481caf756516ae1043212dcdc47ab33d2d"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
