name = "Server Thingy"
author = "pixl_xip"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134d49f05d617482004aa950ad0ccf87a5a29c99021f14d28fb231a4805ed619"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
