name = "Server Thingy"
author = "pixl_xip"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0dc63384ab01cc34bf6e98372559990205b88cef308b6c721fd1fb7a496bcf8"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
